project:
  type: website
  output-dir: docs

bibliography: references.bib

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "0^0"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/TaiNing1237/
      # - icon: twitter
      #   href: https://twitter.com
  comments:
    giscus:
      repo: TaiNing1237/quarto-blog
      repo-id: "R_kgDOQX3NUw"       # Get this from giscus.app
      category: "General"         # Must match what you chose on giscus.app
      category-id: "DIC_kwDOQX3NU84Cx6xN" # Get this from giscus.app
      mapping: "pathname"         # This maps blog posts to discussion titles
      theme: "light"              # You can use "dark" or "preferred_color_scheme"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



